<?php

if ($block->getScopeConfig('christmasdecoration/background_image/enable')) {
    $backgroundImgUrl = $block->getBackgroundImgUrl();
    ?>
    <script type="text/javascript">
        'use strict';
        require(['jquery'], function ($) {
            $(document).ready(function () {
                var backgroundImgUrl = '<?php echo $backgroundImgUrl; ?>';
                $('.page-wrapper').css('background-image', 'url("'+backgroundImgUrl+'")');
            });
        });
    </script>

    <?php

}
?>