<?php
if ($block->getScopeConfig('christmasdecoration/background_image/enable') && $block->isEnableDecoration()) {
    $backgroundImgUrl = $block->getBackgroundImgUrl();
    if ($backgroundImgUrl) {
        ?>
        <script type="text/javascript">
            'use strict';
            require(['jquery'], function ($) {
                $(document).ready(function () {
                    var backgroundImgUrl = '<?php echo $backgroundImgUrl; ?>';
                    $('body').css('background-image', 'url("' + backgroundImgUrl + '")');
                });
            });
        </script>

        <?php
    }
}
?>