<?php
/**
 * @copyright Copyright (c) 2016 www.magebuzz.com
 */
if ($block->getScopeConfig('christmasdecoration/moving_image/enable') && $block->isEnableDecoration()) {
    $movingImgUrl = $block->getMovingImgUrl();
    if ($movingImgUrl) {
        $duration = $block->getScopeConfig('christmasdecoration/moving_image/duration');
        $speed = $block->getScopeConfig('christmasdecoration/moving_image/speed');
        $direction = $block->getScopeConfig('christmasdecoration/moving_image/direction');
        ?>
        <div class="christmas_moving_img">
            <img src="<?php echo $movingImgUrl; ?>" />
        </div>
        <script type="text/javascript">
            'use strict';
            require(['jquery'], function ($) {
                $(document).ready(function () {
                    function ChristmasMoving() {
                        var step = 1;
                        var speed = <?php echo $speed; ?>;
                        var interval = 50 * step / speed;

                        var count = 0;
                        var duration = '<?php echo $duration; ?>';
                        var maxcount = duration * 1000 / interval;

                        var direction = '<?php echo $direction; ?>';
                        InitMoving();
                        var movingTimer = setInterval(function () {
                            moving()
                        }, interval);

                        var left = 0, right = 0, top = 0, bottom = 0;
                        var topInc = (Math.random() * 10 > 5) ? step : -step;
                        var leftInc = (Math.random() * 10 > 5) ? step : -step;

                        function InitMoving() {
                            if (direction == 'left_to_right') {
                                $('.christmas_moving_img').css({top: '0', left: -$('.christmas_moving_img').width()});
                            } else if (direction == 'right_to_left') {
                                $('.christmas_moving_img').css({top: '0', left: $(window).width()});
                            } else if (direction == 'top_to_bottom') {
                                $('.christmas_moving_img').css({top: -$('.christmas_moving_img').height(), left: '0'});
                            } else if (direction == 'bottom_to_top') {
                                $('.christmas_moving_img').css({top: $(window).height(), left: '0'});
                            } else if (direction == 'random') {
                                var initTopPos = Math.floor(Math.random() * ($(window).height() - $('.christmas_moving_img').height()));
                                var initLeftPos = Math.floor(Math.random() * ($(window).width() - $('.christmas_moving_img').width()));
                                $('.christmas_moving_img').css({top: initTopPos, left: initLeftPos});
                            }
                            $('.christmas_moving_img').show();

                            $('.christmas_moving_img').click(function () {
                                $(this).remove();
                                clearInterval(movingTimer);
                            });
                        }

                        function moving() {
                            if (direction == 'left_to_right') {
                                left = $('.christmas_moving_img').css('left');
                                if (parseInt(left) >= $(window).width()) {
                                    left = 0 - $('.christmas_moving_img').width();
                                    top = Math.ceil(Math.random() * ($(window).height() - $('.christmas_moving_img').height()));
                                    $('.christmas_moving_img').css('top', top);
                                }
                                $('.christmas_moving_img').css('left', parseInt(left) + step);
                            } else if (direction == 'right_to_left') {
                                left = $('.christmas_moving_img').css('left');
                                if (parseInt(left) + $('.christmas_moving_img').width() <= 0) {
                                    left = $(window).width();
                                    top = Math.ceil(Math.random() * ($(window).height() - $('.christmas_moving_img').height()));
                                    $('.christmas_moving_img').css('top', top);
                                }
                                $('.christmas_moving_img').css('left', parseInt(left) - step);
                            } else if (direction == 'top_to_bottom') {
                                top = $('.christmas_moving_img').css('top');
                                if (parseInt(top) >= $(window).height()) {
                                    top = 0 - $('.christmas_moving_img').height();
                                    left = Math.ceil(Math.random() * ($(window).width() - $('.christmas_moving_img').width()));
                                    $('.christmas_moving_img').css('left', left);
                                }
                                $('.christmas_moving_img').css('top', parseInt(top) + step);
                            } else if (direction == 'bottom_to_top') {
                                top = $('.christmas_moving_img').css('top');
                                if (parseInt(top) + $('.christmas_moving_img').height() <= 0) {
                                    top = $(window).height();
                                    left = Math.ceil(Math.random() * ($(window).width() - $('.christmas_moving_img').width()));
                                    $('.christmas_moving_img').css('left', left);
                                }
                                $('.christmas_moving_img').css('top', parseInt(top) - step);
                            } else if (direction == 'random') {
                                top = $('.christmas_moving_img').css('top');
                                left = $('.christmas_moving_img').css('left');

                                if (parseInt(top) <= 0) {
                                    topInc = step;
                                } else if (parseInt(top) + $('.christmas_moving_img').height() >= $(window).height()) {
                                    topInc = -step;
                                }
                                if (parseInt(left) <= 0) {
                                    leftInc = step;
                                } else if (parseInt(left) + $('.christmas_moving_img').width() >= $(window).width()) {
                                    leftInc = -step;
                                }
                                $('.christmas_moving_img').css('top', parseInt(top) + topInc);
                                $('.christmas_moving_img').css('left', parseInt(left) + leftInc);
                            }

                            count++;
                            if (count == maxcount) {
                                clearInterval(movingTimer);
                                $('.christmas_moving_img').remove();
                            }
                        }
                    }
                    ChristmasMoving();
                });
            });
        </script>

        <?php
    }
}
?>