<?php

if ($block->getScopeConfig('christmasdecoration/moving_image/enable')) {
    $movingImgUrl = $block->getMovingImgUrl();
    $duration = $block->getScopeConfig('christmasdecoration/moving_image/duration');
    $speed = $block->getScopeConfig('christmasdecoration/moving_image/speed');
    $direction = $block->getScopeConfig('christmasdecoration/moving_image/direction');
    ?>
    <div class="christmas_moving_img">
        <img src="<?php echo $movingImgUrl; ?>" />
    </div>
    <script type="text/javascript">
        'use strict';
        require(['jquery'], function ($) {
            $(document).ready(function () {
                var speed = <?php echo $speed; ?>;
                var interval = 50 / speed;
                
                var count = 0;
                var duration = '<?php echo $duration; ?>';
                var maxcount = duration * 1000 / interval;
                
                var direction = '<?php echo $direction; ?>';
                var movingTimer = setInterval(function() {moving()}, interval) ;
                
                var left = 0, right = 0, top = 0, bottom = 0;
                var topInc = (Math.random() * 10 > 5) ? 1 : -1
                var leftInc = (Math.random() * 10 > 5) ? 1 : -1
                
                $('.christmas_moving_img').click(function() {
                    $(this).remove();
                    clearInterval(movingTimer);
                });
                if (direction == 'left_to_right') {
                    $('.christmas_moving_img').css({top:'0', left: -$('.christmas_moving_img').width()});
                } else if (direction == 'right_to_left') {
                    $('.christmas_moving_img').css({top:'0', left: $(window).width()});
                } else if (direction == 'top_to_bottom') {
                    $('.christmas_moving_img').css({top:-$('.christmas_moving_img').height(), left:'0'});
                } else if (direction == 'bottom_to_top') {
                    $('.christmas_moving_img').css({top:$(window).height(), left:'0'});
                } else if (direction == 'random') {
                    $('.christmas_moving_img').css({top:$(window).height()/2, left:$(window).width()/2});
                }
                $('.christmas_moving_img').show();
                function moving() {
                    if (direction == 'left_to_right') {
                        left = $('.christmas_moving_img').css('left');
                        if (parseInt(left) >= $(window).width()) {
                            left = 0 - $('.christmas_moving_img').width();
                            top = Math.ceil(Math.random() * ($(window).height() - $('.christmas_moving_img').height()));
                            $('.christmas_moving_img').css('top', top);
                        }
                        $('.christmas_moving_img').css('left', parseInt(left) + 1);
                    } else if (direction == 'right_to_left') {
                        left = $('.christmas_moving_img').css('left');
                        if (parseInt(left) + $('.christmas_moving_img').width() <= 0) {
                            left = $(window).width();
                            top = Math.ceil(Math.random() * ($(window).height() - $('.christmas_moving_img').height()));
                            $('.christmas_moving_img').css('top', top);
                        }
                        $('.christmas_moving_img').css('left', parseInt(left) - 1);
                    } else if (direction == 'top_to_bottom') {
                        top = $('.christmas_moving_img').css('top');
                        if (parseInt(top) >= $(window).height()) {
                            top = 0 - $('.christmas_moving_img').height();
                            left = Math.ceil(Math.random() * ($(window).width() - $('.christmas_moving_img').width()));
                            $('.christmas_moving_img').css('left', left);
                        }
                        $('.christmas_moving_img').css('top', parseInt(top) + 1);
                    } else if (direction == 'bottom_to_top') {
                        top = $('.christmas_moving_img').css('top');
                        if (parseInt(top) + $('.christmas_moving_img').height() <= 0) {
                            top = $(window).height();
                            left = Math.ceil(Math.random() * ($(window).width() - $('.christmas_moving_img').width()));
                            $('.christmas_moving_img').css('left', left);
                        }
                        $('.christmas_moving_img').css('top', parseInt(top) - 1);
                    } else if (direction == 'random') {
                        top = $('.christmas_moving_img').css('top');
                        left = $('.christmas_moving_img').css('left');
                        
                        if (parseInt(top) <= 0) {
                            topInc = 1;
                        } else if (parseInt(top) + $('.christmas_moving_img').height() >= $(window).height()) {
                            topInc = -1;
                        }
                        if (parseInt(left) <= 0) {
                            leftInc = 1;
                        } else if (parseInt(left) + $('.christmas_moving_img').width() >= $(window).width()) {
                            leftInc = -1;
                        }
                        $('.christmas_moving_img').css('top', parseInt(top) + topInc);
                        $('.christmas_moving_img').css('left', parseInt(left) + leftInc);
                    }
                    
                    count++;
                    if (count == maxcount) {
                        clearInterval(movingTimer);
                        $('.christmas_moving_img').remove();
                    }
                }
                    
            });
        });
    </script>

    <?php

}
?>