<?php
if ($block->getScopeConfig('christmasdecoration/snowfall/enable') && $block->isEnableDecoration()) {
    $snowfallImgUrls = $block->getSnowfallImgUrls();
    if ($snowfallImgUrls) {
        $numOfSnowflakes = $block->getScopeConfig('christmasdecoration/snowfall/num_of_snowflakes');
        $speed = $block->getScopeConfig('christmasdecoration/snowfall/speed');
        $minSize = $block->getScopeConfig('christmasdecoration/snowfall/min_size');
        $maxSize = $block->getScopeConfig('christmasdecoration/snowfall/max_size');
        $effect = $block->getScopeConfig('christmasdecoration/snowfall/effect');
        ?>
        <script type="text/javascript">
        //        'use strict';
            require(['jquery'], function ($) {
                $(document).ready(function () {
                    var numOfSnowflakes = <?php echo $numOfSnowflakes; ?>;
                    numOfSnowflakes = numOfSnowflakes ? numOfSnowflakes : 30;
                    var speed = <?php echo $speed; ?>;
                    var interval = 100 / speed;
                    var effect = '<?php echo $effect; ?>';
                    var minSize = <?php echo $minSize; ?>;
                    var maxSize = <?php echo $maxSize; ?>;
                    var imgUrls = '<?php echo $snowfallImgUrls; ?>';
                    var imgUrlArr = imgUrls.split(',');
                    var imgUrlArrLen = imgUrlArr.length;

                    for (var i = 0; i < numOfSnowflakes; i++)
                    {
                        do {
                            var size = Math.ceil(Math.random() * maxSize);
                        } while (size < minSize);
                        var urlIndex = Math.floor(Math.random() * imgUrlArrLen);
                        var url = imgUrlArr[urlIndex];
                        if (effect == 'swing') {
                            var count = Math.floor(Math.random() * 300);
                        } else {
                            var count = '';
                        }
                        var snowflakeHtml = '<img class="christmas snowflake" src="' + url + '" style="height:' + size + 'px; width:' + size + 'px;" data-count="' + count + '" />';
                        $('body').append(snowflakeHtml);
                    }

                    function InitSnowfall() {
                        $('.christmas.snowflake').each(function () {
                            var leftPos = Math.floor(Math.random() * ($(window).width() - $(this).width()));
                            var topPos = Math.floor(Math.random() * ($(window).height() - $(this).height()));
                            $(this).css({left: leftPos, top: topPos});

                            var leftInc = (Math.random() * 10 > 5) ? 1 : -1;
                            $(this).data('dir', leftInc);
                        });

                    }

                    function Snowfall()
                    {
                        $('.christmas.snowflake').each(function (i) {
                            var left = parseInt($(this).css('left'));
                            var top = parseInt($(this).css('top'));
                            if (effect == 'swing') {
                                if (top >= $(window).height() || left >= $(window).width()) {
                                    top = 0 - $(this).height();
                                    left = Math.floor(Math.random() * ($(window).width() - $(this).width()));
                                }
                                var count = $(this).data('count');
                                if (count == 300) {
                                    $(this).data('dir', 0 - $(this).data('dir'));
                                    count = 0;
                                }
                                $(this).data('count', count + 1);
                                var leftInc = parseInt($(this).data('dir'));
                                $(this).css({left: left + leftInc, top: top + 1});

                            } else if (effect == 'cross') {
                                if (top >= $(window).height() || left >= $(window).width()) {
                                    top = 0 - $(this).height();
                                    left = Math.floor(Math.random() * ($(window).width() - $(this).width()));
                                }
                                var leftInc = $(this).data('dir') ? parseInt($(this).data('dir')) : 1;
                                $(this).css({left: left + leftInc, top: top + 1});

                            } else if (effect == 'suspended') {
                                if (left == $(window).width()) {    //to right side
                                    left = 0;
                                }
                                if (left + $(this).width() <= 0) {    //to left side
                                    left = $(window).width();
                                }
                                var leftInc = $(this).data('dir') ? parseInt($(this).data('dir')) : 1;
                                $(this).css('left', left + leftInc);
                            }
                        });

                    }
                    InitSnowfall();
                    setInterval(function () {
                        Snowfall()
                    }, interval);
                });
            });
        </script>
        <?php
    }
}
?>